export * from "./message";
export * from "./server";
export * from "./member";
export * from "./channel";
export * from "./webhook";

export enum WebSocketEvent {
    BotServerMembershipCreated = "BotServerMembershipCreated",
    BotServerMembershipDeleted = "BotServerMembershipDeleted",
    ChatMessageCreated = "ChatMessageCreated",
    ChatMessageUpdated = "ChatMessageUpdated",
    ChatMessageDeleted = "ChatMessageDeleted",
    ServerMemberJoined = "ServerMemberJoined",
    ServerMemberRemoved = "ServerMemberRemoved",
    ServerMemberBanned = "ServerMemberBanned",
    ServerMemberUnbanned = "ServerMemberUnbanned",
    ServerMemberUpdated = "ServerMemberUpdated",
    ServerRolesUpdated = "ServerRolesUpdated",
    ServerChannelCreated = "ServerChannelCreated",
    ServerChannelUpdated = "ServerChannelUpdated",
    ServerChannelDeleted = "ServerChannelDeleted",
    ServerMemberSocialLinkCreated = "ServerMemberSocialLinkCreated",
    ServerMemberSocialLinkUpdated = "ServerMemberSocialLinkUpdated",
    ServerMemberSocialLinkDeleted = "ServerMemberSocialLinkDeleted",
    ServerWebhookCreated = "ServerWebhookCreated",
    ServerWebhookUpdated = "ServerWebhookUpdated",
    DocCreated = "DocCreated",
    DocUpdated = "DocUpdated",
    DocDeleted = "DocDeleted",
    DocCommentCreated = "DocCommentCreated",
    DocCommentDeleted = "DocCommentDeleted",
    DocCommentUpdated = "DocCommentUpdated",
    CalendarEventCreated = "CalendarEventCreated",
    CalendarEventUpdated = "CalendarEventUpdated",
    CalendarEventDeleted = "CalendarEventDeleted",
    ForumTopicCreated = "ForumTopicCreated",
    ForumTopicUpdated = "ForumTopicUpdated",
    ForumTopicDeleted = "ForumTopicDeleted",
    ForumTopicPinned = "ForumTopicPinned",
    ForumTopicUnpinned = "ForumTopicUnpinned",
    ForumTopicReactionCreated = "ForumTopicReactionCreated",
    ForumTopicReactionDeleted = "ForumTopicReactionDeleted",
    ForumTopicLocked = "ForumTopicLocked",
    ForumTopicUnlocked = "ForumTopicUnlocked",
    ForumTopicCommentCreated = "ForumTopicCommentCreated",
    ForumTopicCommentUpdated = "ForumTopicCommentUpdated",
    ForumTopicCommentDeleted = "ForumTopicCommentDeleted",
    CalendarEventRsvpUpdated = "CalendarEventRsvpUpdated",
    CalendarEventRsvpManyUpdated = "CalendarEventRsvpManyUpdated",
    CalendarEventRsvpDeleted = "CalendarEventRsvpDeleted",
    ListItemCreated = "ListItemCreated",
    ListItemUpdated = "ListItemUpdated",
    ListItemDeleted = "ListItemDeleted",
    ListItemCompleted = "ListItemCompleted",
    ListItemUncompleted = "ListItemUncompleted",
    ChannelMessageReactionCreated = "ChannelMessageReactionCreated",
    ChannelMessageReactionDeleted = "ChannelMessageReactionDeleted",
    ChannelMessageReactionManyDeleted = "ChannelMessageReactionManyDeleted",
    ForumTopicCommentReactionCreated = "ForumTopicCommentReactionCreated",
    ForumTopicCommentReactionDeleted = "ForumTopicCommentReactionDeleted",
};